name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          ref: 'main'

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
          scope: '@leandrogrillo'

      - name: Setup github account
        run: |
          git config --global user.name ${{ github.event.pusher.name }}
          git config --global user.email ${{ github.event.pusher.email }}
      
      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          branch: 'package-version-${{ github.sha }}'

      - name: Checkout to ${{ github.sha }}
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          ref: 'package-version-${{ github.sha }}'

      - name: Install
        run: yarn

      - name: Release
        run: yarn lerna publish --conventional-commits --yes

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: 'package-version-${{ github.sha }}'
          destination_branch: 'main'
          pr_assignee: 'leandrogrillo'
          pr_title: 'chore: update package versions'
          pr_template: '.github/workflows/templates/release.md'
          github_token: ${{ secrets.PAT }}
