name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GIT_BOT_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          ref: 'main'

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
          scope: '@leroy-merlin-br'

      - name: Install
        run: yarn

      - name: Release
        run: yarn lerna publish --conventional-commits --yes
